# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/asp/skeleton

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/asp/skeleton

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/asp/skeleton/CMakeFiles /home/asp/skeleton//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/asp/skeleton/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named v8wrapper

# Build rule for target.
v8wrapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 v8wrapper
.PHONY : v8wrapper

# fast build rule for target.
v8wrapper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v8wrapper.dir/build.make CMakeFiles/v8wrapper.dir/build
.PHONY : v8wrapper/fast

#=============================================================================
# Target rules for targets named asp_v8

# Build rule for target.
asp_v8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asp_v8
.PHONY : asp_v8

# fast build rule for target.
asp_v8/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/build
.PHONY : asp_v8/fast

#=============================================================================
# Target rules for targets named codegrade_tests

# Build rule for target.
codegrade_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegrade_tests
.PHONY : codegrade_tests

# fast build rule for target.
codegrade_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codegrade_tests.dir/build.make CMakeFiles/codegrade_tests.dir/build
.PHONY : codegrade_tests/fast

#=============================================================================
# Target rules for targets named submission

# Build rule for target.
submission: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 submission
.PHONY : submission

# fast build rule for target.
submission/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/submission.dir/build.make CMakeFiles/submission.dir/build
.PHONY : submission/fast

src/m1_2__simple_server.o: src/m1_2__simple_server.c.o
.PHONY : src/m1_2__simple_server.o

# target to build an object file
src/m1_2__simple_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/m1_2__simple_server.c.o
.PHONY : src/m1_2__simple_server.c.o

src/m1_2__simple_server.i: src/m1_2__simple_server.c.i
.PHONY : src/m1_2__simple_server.i

# target to preprocess a source file
src/m1_2__simple_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/m1_2__simple_server.c.i
.PHONY : src/m1_2__simple_server.c.i

src/m1_2__simple_server.s: src/m1_2__simple_server.c.s
.PHONY : src/m1_2__simple_server.s

# target to generate assembly for a file
src/m1_2__simple_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/m1_2__simple_server.c.s
.PHONY : src/m1_2__simple_server.c.s

src/m3__multi_threaded_server.o: src/m3__multi_threaded_server.c.o
.PHONY : src/m3__multi_threaded_server.o

# target to build an object file
src/m3__multi_threaded_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/m3__multi_threaded_server.c.o
.PHONY : src/m3__multi_threaded_server.c.o

src/m3__multi_threaded_server.i: src/m3__multi_threaded_server.c.i
.PHONY : src/m3__multi_threaded_server.i

# target to preprocess a source file
src/m3__multi_threaded_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/m3__multi_threaded_server.c.i
.PHONY : src/m3__multi_threaded_server.c.i

src/m3__multi_threaded_server.s: src/m3__multi_threaded_server.c.s
.PHONY : src/m3__multi_threaded_server.s

# target to generate assembly for a file
src/m3__multi_threaded_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/m3__multi_threaded_server.c.s
.PHONY : src/m3__multi_threaded_server.c.s

src/m4_5__event_based_server.o: src/m4_5__event_based_server.c.o
.PHONY : src/m4_5__event_based_server.o

# target to build an object file
src/m4_5__event_based_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/m4_5__event_based_server.c.o
.PHONY : src/m4_5__event_based_server.c.o

src/m4_5__event_based_server.i: src/m4_5__event_based_server.c.i
.PHONY : src/m4_5__event_based_server.i

# target to preprocess a source file
src/m4_5__event_based_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/m4_5__event_based_server.c.i
.PHONY : src/m4_5__event_based_server.c.i

src/m4_5__event_based_server.s: src/m4_5__event_based_server.c.s
.PHONY : src/m4_5__event_based_server.s

# target to generate assembly for a file
src/m4_5__event_based_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/m4_5__event_based_server.c.s
.PHONY : src/m4_5__event_based_server.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/main.c.s
.PHONY : src/main.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asp_v8.dir/build.make CMakeFiles/asp_v8.dir/src/utils.c.s
.PHONY : src/utils.c.s

src/v8_api_access.o: src/v8_api_access.cc.o
.PHONY : src/v8_api_access.o

# target to build an object file
src/v8_api_access.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v8wrapper.dir/build.make CMakeFiles/v8wrapper.dir/src/v8_api_access.cc.o
.PHONY : src/v8_api_access.cc.o

src/v8_api_access.i: src/v8_api_access.cc.i
.PHONY : src/v8_api_access.i

# target to preprocess a source file
src/v8_api_access.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v8wrapper.dir/build.make CMakeFiles/v8wrapper.dir/src/v8_api_access.cc.i
.PHONY : src/v8_api_access.cc.i

src/v8_api_access.s: src/v8_api_access.cc.s
.PHONY : src/v8_api_access.s

# target to generate assembly for a file
src/v8_api_access.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/v8wrapper.dir/build.make CMakeFiles/v8wrapper.dir/src/v8_api_access.cc.s
.PHONY : src/v8_api_access.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... codegrade_tests"
	@echo "... submission"
	@echo "... asp_v8"
	@echo "... v8wrapper"
	@echo "... src/m1_2__simple_server.o"
	@echo "... src/m1_2__simple_server.i"
	@echo "... src/m1_2__simple_server.s"
	@echo "... src/m3__multi_threaded_server.o"
	@echo "... src/m3__multi_threaded_server.i"
	@echo "... src/m3__multi_threaded_server.s"
	@echo "... src/m4_5__event_based_server.o"
	@echo "... src/m4_5__event_based_server.i"
	@echo "... src/m4_5__event_based_server.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/v8_api_access.o"
	@echo "... src/v8_api_access.i"
	@echo "... src/v8_api_access.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

